/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobsfordesigners;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static jobsfordesigners.JobsForDesigners.BASE;
import static jobsfordesigners.JobsForDesigners.PASSWORD;
import static jobsfordesigners.JobsForDesigners.SERVER;
import static jobsfordesigners.JobsForDesigners.USER;
import static jobsfordesigners.JobsForDesigners.User;

/**
 *
 * @author Nezhdanoff
 */
public class JOB_Jornal_JFrame extends javax.swing.JFrame {

    private final DefaultListModel KDO_Model = new DefaultListModel();
    private final DefaultListModel Customer_List_Model = new DefaultListModel();
    private final DefaultComboBoxModel Manager_CB_Model = new DefaultComboBoxModel();
    /**
     * Creates new form JOB_Jornal_JFrame
     */
    JOB_Jornal_JFrame() {

        initComponents();

        KDO_Model.clear();
        Customer_List_Model.clear();
        Manager_CB_Model.removeAllElements();

//        JL_KindList.setModel(KDO_Model);
        LB_FIO_Redactor.setText(User.getEmp_Surname() + " " + User.getEmp_Name());
 //       DefaultComboBoxModel Manager_CB_Model = new DefaultComboBoxModel();

        // подключаемся к базе и вытаскиваем из нее данные
        // Заполняем ComboBox Менеджеры
        String Query = "SELECT "
                + "employers.ID AS emp_ID, "
                + "CONCAT_WS(' ', employers.surname, employers.name) AS emp_Name "
                + "FROM employers "
                + "WHERE employers.department_ID = 2 "
                + "ORDER BY employers.surname, employers.name";

        ConnectDB conn = new ConnectDB(SERVER, USER, PASSWORD, BASE);
        conn.init();
        ResultSet rs = conn.query(Query);
        try {
            while (rs.next()) {
                // СОЗДАЕМ ОБЪЕКТ НА ОСНОВЕ ПОЛУЧЕННЫХ ДАННЫХ
                ComboBoxDataObject CB_Object = new ComboBoxDataObject(
                        rs.getInt("emp_ID"),
                        rs.getString("emp_Name"));
                // ДОБАВЛЯЕМ ЭТОТ ОБЪЕКТ В МОДЕЛЬ
                Manager_CB_Model.addElement(CB_Object);
            }
            // ВСТАВЛЯЕМ ДАННЫЕ МОДЕЛИ В ComboBox
            CB_Manager.setModel(Manager_CB_Model);
        } catch (SQLException ex) {
            Logger.getLogger(LoginJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        conn.close();
        CB_Manager.setSelectedIndex(-1);
        //***********************************************************************
        // Определяем Listener поискового текстового поля

        TF_Customer.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {

            Customer_List_Model.clear();
                // подключаемся к базе и вытаскиваем из нее данные
                // Заполняем ComboBox Менеджеры
                String Query = "CALL GetCustomerDataObjectByFilter('"
                        + TF_Customer.getText() + "')";
                ConnectDB conn = new ConnectDB(SERVER, USER, PASSWORD, BASE);
                conn.init();
                ResultSet rs = conn.query(Query);
                try {
                    while (rs.next()) {
                        // СОЗДАЕМ ОБЪЕКТ НА ОСНОВЕ ПОЛУЧЕННЫХ ДАННЫХ
                        CustomerDataObject Customer_Object = new CustomerDataObject(
                                rs.getInt("cust_ID"),
                                rs.getString("cust_Alias"),
                                rs.getString("cust_Name"));
                        // ДОБАВЛЯЕМ ЭТОТ ОБЪЕКТ В МОДЕЛЬ
                        Customer_List_Model.addElement(Customer_Object);
                    }
                    JL_Customers.setModel(Customer_List_Model);
                } catch (SQLException ex) {
                    Logger.getLogger(LoginJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                conn.close();
            }
        });
        //***********************************************************************
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Job_Number = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TF_Job_Number = new javax.swing.JTextField();
        TF_TM = new javax.swing.JTextField();
        LB_FIO_Redactor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_Job_Number1 = new javax.swing.JLabel();
        TF_Customer = new javax.swing.JTextField();
        TF_NameOfKind = new javax.swing.JTextField();
        TF_Volume = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JL_KindList = new javax.swing.JList<>();
        JB_AddKind = new javax.swing.JButton();
        JB_AddJOB = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        CB_Unit = new javax.swing.JComboBox<>();
        CB_Manager = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_Customers = new javax.swing.JList<>();
        JL_Cust_ID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_Job_Number2 = new javax.swing.JLabel();
        jLabel_Job_Number3 = new javax.swing.JLabel();
        jLabel_Job_Number4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel_Job_Number5 = new javax.swing.JLabel();
        jLabel_Job_Number6 = new javax.swing.JLabel();
        jLabel_Job_Number7 = new javax.swing.JLabel();
        jLabel_Job_Number8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Job_Number.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Job_Number.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Job_Number.setText("№ ТЗ");
        jPanel2.add(jLabel_Job_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 60, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Фильтр");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, 68, -1));

        TF_Job_Number.setNextFocusableComponent(CB_Manager);
        TF_Job_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_Job_NumberActionPerformed(evt);
            }
        });
        TF_Job_Number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_Job_NumberFocusLost(evt);
            }
        });
        jPanel2.add(TF_Job_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 4, 62, -1));

        TF_TM.setNextFocusableComponent(TF_NameOfKind);
        jPanel2.add(TF_TM, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 236, 433, -1));

        LB_FIO_Redactor.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        LB_FIO_Redactor.setForeground(new java.awt.Color(0, 0, 204));
        LB_FIO_Redactor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LB_FIO_Redactor.setText(" ");
        jPanel2.add(LB_FIO_Redactor, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 5, 241, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText(" ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 5, 73, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 5, 56, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Торговая Марка");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 238, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Название Вида");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 264, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Масса (Объем)");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 291, -1, -1));

        jLabel_Job_Number1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Job_Number1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Job_Number1.setText("Менеджер");
        jPanel2.add(jLabel_Job_Number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, -1));

        TF_Customer.setNextFocusableComponent(JL_Customers);
        jPanel2.add(TF_Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 464, -1));

        TF_NameOfKind.setNextFocusableComponent(TF_Volume);
        jPanel2.add(TF_NameOfKind, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 262, 433, -1));

        TF_Volume.setNextFocusableComponent(CB_Unit);
        jPanel2.add(TF_Volume, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 289, 121, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Виды; Масса (Объем)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL_KindList.setModel(KDO_Model);
        jScrollPane2.setViewportView(JL_KindList);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 445, 95));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 320, 460, 120));

        JB_AddKind.setMnemonic('+');
        JB_AddKind.setText("Добавить этот ВИД");
        JB_AddKind.setNextFocusableComponent(TF_NameOfKind);
        JB_AddKind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AddKindActionPerformed(evt);
            }
        });
        jPanel2.add(JB_AddKind, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 288, 142, -1));

        JB_AddJOB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JB_AddJOB.setText("<html><center>Внести<br>запись в<br>журнал</html>");
        JB_AddJOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AddJOBActionPerformed(evt);
            }
        });
        jPanel2.add(JB_AddJOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 285, 85, 76));

        jButton3.setText("Очистить");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 365, 83, -1));

        jButton4.setText("Выход");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 395, 83, 44));

        CB_Unit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "кг.", "г.", "мг.", "л.", "мл." }));
        CB_Unit.setSelectedIndex(-1);
        CB_Unit.setToolTipText("");
        CB_Unit.setNextFocusableComponent(JB_AddKind);
        CB_Unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_UnitActionPerformed(evt);
            }
        });
        jPanel2.add(CB_Unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 289, 53, -1));

        CB_Manager.setModel(Manager_CB_Model);
        CB_Manager.setNextFocusableComponent(TF_Customer);
        CB_Manager.setRenderer(new CB_DataRenderer("ВЫБЕРИТЕ МЕНЕДЖЕРА"));
        CB_Manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_ManagerActionPerformed(evt);
            }
        });
        jPanel2.add(CB_Manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 30, 323, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Заказчик"));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL_Customers.setModel(Customer_List_Model);
        JL_Customers.setNextFocusableComponent(TF_TM);
        JL_Customers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                JL_CustomersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(JL_Customers);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 535, 125));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 550, 150));

        JL_Cust_ID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        JL_Cust_ID.setText(" ");
        jPanel2.add(JL_Cust_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 33, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 565, -1));

        jLabel1.setText(" ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 445, 545, 20));

        jTabbedPane1.addTab("Ввод новых ТЗ", jPanel1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jLabel4.setText(" ");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("01.01.2016");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("23:59:00");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addGap(124, 124, 124)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jLabel9))
            .addComponent(jLabel10)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ОК", "Не соответствует требованиям", "Не хватает материалов, файлов" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ТЗ №", "Менеджер", "Заказчик", "Заказ"
            }
        ));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jTable1);

        jLabel_Job_Number2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Job_Number2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Job_Number2.setText("Статус после проверки");

        jLabel_Job_Number3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Job_Number3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Job_Number3.setText("Вид работы");

        jLabel_Job_Number4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Job_Number4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Job_Number4.setText("Сложность");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ОК", "Не соответствует требованиям", "Не хватает материалов, файлов" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ОК", "Не соответствует требованиям", "Не хватает материалов, файлов" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel_Job_Number5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Job_Number5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Job_Number5.setText("Время минимум");

        jLabel_Job_Number6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Job_Number6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Job_Number6.setText("Время максимум");

        jLabel_Job_Number7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Job_Number7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Job_Number7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Job_Number7.setText("240");

        jLabel_Job_Number8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Job_Number8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_Job_Number8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Job_Number8.setText("240");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_Job_Number3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Job_Number2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_Job_Number5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_Job_Number6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Job_Number8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Job_Number7, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_Job_Number4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Job_Number2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Job_Number5)
                            .addComponent(jLabel_Job_Number7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Job_Number3)
                            .addComponent(jLabel_Job_Number6)
                            .addComponent(jLabel_Job_Number8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Job_Number4)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Первая проверка", jPanel3);

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ТЗ №1646 [Менеджер:] Бортниченко [Заказчик:] Вінницька ПФ [Заказ:] Qualiko 1800 ЕС", "ТЗ №1705 [Менеджер:] Бец [Заказчик:] Лобода [Заказ:] Специи 1кг", "ТЗ №1710 [Менеджер:] Чёрная [Заказчик:] Оболонь [Заказ:] Живчик яблоко 2л Беларусь", "ТЗ №1729 [Менеджер:] Приходько [Заказчик:] Глюдор [Заказ:] Корм замороженный для ТМ Кардинал", "ТЗ №1622 [Менеджер:] Курдияк [Заказчик:] Бон Буассон [Заказ:] Бон Лимон лимонад бузина, лимонад малина", "ТЗ №1735 [Менеджер:] Лунгол [Заказчик:] СПД Поп  [Заказ:] Насіння Херсонське", "ТЗ №1722 [Менеджер:] Мартушканова [Заказчик:] Слесь [Заказ:] ТМ Запоріжжя ПСБ Смачненьки 150г", "ТЗ №1743 [Менеджер:] Бец [Заказчик:] Букпак(Писаренко) [Заказ:] Цукор 0,75   Гречка 0,75", "ТЗ №1753 [Менеджер:] Приходько [Заказчик:] КБФ [Заказ:] Рулет бісквітний Рулетте №1 150г з какао, абрикосовий, полуничний, молочний", "ТЗ №1763 [Менеджер:] Приходько [Заказчик:] ФЗП  [Заказ:] Вареники з картоплею ТМ Ласка 900г", "ТЗ №1764 [Менеджер:] Приходько [Заказчик:] Лавка здоровья [Заказ:] Хлебцы маленькие", "ТЗ №1660 [Менеджер:] Бортниченко [Заказчик:] Мировівська ПФ [Заказ:] Qualiko 1000 ", "ТЗ №1752 [Менеджер:] Бец [Заказчик:] Поливкан [Заказ:] Семечки 150г Vip" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Алешин С.", "Белик Л.", "Бица И.", "Голобородько А.", "Корогод С.", "Креминская Л.", "Лоза С.", "Мартыненко О.", "Морозов С.", "Опанасенко М.", "Чекмасов Б.", " " }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Назначение Исполнителя", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 575, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CB_ManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_ManagerActionPerformed
        DefaultListModel Customer_List_Model = new DefaultListModel();

        // подключаемся к базе и вытаскиваем из нее данные
        // Заполняем ComboBox Менеджеры
        int managerID = -1;
        if (CB_Manager.getSelectedIndex() >= 0) {
            managerID = ((ComboBoxDataObject) CB_Manager.getSelectedItem()).getField1();

            String Query = "CALL GetCustomerDataObjectsByManagerID("
                    //                + managerID + ")";
                    + "0" + ")";
            ConnectDB conn = new ConnectDB(SERVER, USER, PASSWORD, BASE);
            conn.init();
            ResultSet rs = conn.query(Query);
            try {
                while (rs.next()) {
                    // СОЗДАЕМ ОБЪЕКТ НА ОСНОВЕ ПОЛУЧЕННЫХ ДАННЫХ
                    CustomerDataObject Customer_Object = new CustomerDataObject(
                            rs.getInt("cust_ID"),
                            rs.getString("cust_Alias"),
                            rs.getString("cust_Name"));
                    // ДОБАВЛЯЕМ ЭТОТ ОБЪЕКТ В МОДЕЛЬ
                    Customer_List_Model.addElement(Customer_Object);
                }
                JL_Customers.setModel(Customer_List_Model);
            } catch (SQLException ex) {
                Logger.getLogger(LoginJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            conn.close();
        }
    }//GEN-LAST:event_CB_ManagerActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void JL_CustomersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_JL_CustomersValueChanged
        int i = JL_Customers.getSelectedIndex();
        Object obj = JL_Customers.getModel().getElementAt(i);
        if (obj instanceof CustomerDataObject) {
            CustomerDataObject item = (CustomerDataObject) obj;
            JL_Cust_ID.setText(Integer.toString(item.getCust_ID()));
            TF_Customer.setText(item.getCust_Name());
        }
    }//GEN-LAST:event_JL_CustomersValueChanged

    private void JB_AddKindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AddKindActionPerformed
        String K = TF_NameOfKind.getText().trim().toUpperCase();
//        String FF = TF_Volume.getText().trim().replace(",", ".");
        try {
            float V = Float.parseFloat(TF_Volume.getText().trim().replace(",", "."));
            String U = CB_Unit.getSelectedItem().toString().trim();
            KindDataObject iKind = new KindDataObject(K, V, U);
            KDO_Model.addElement(iKind);
        } catch (Exception e) {
            KindDataObject iKind = new KindDataObject(K);
            KDO_Model.addElement(iKind);
        }
    }//GEN-LAST:event_JB_AddKindActionPerformed

    private void JB_AddJOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AddJOBActionPerformed
        String CName = "";
        String output;
        String query = "";
        String query1 = "";
        String query2 = "";
        int i = JL_Customers.getSelectedIndex();
        int cust_ID = 0;
        Object obj = JL_Customers.getModel().getElementAt(i);
        if (obj instanceof CustomerDataObject) {
            CustomerDataObject item = (CustomerDataObject) obj;
            cust_ID = item.getCust_ID();
            CName = item.getCust_Name();
        }
        output = "Заполнил: " + LB_FIO_Redactor.getText() + "\n";
        output = output + "ТЗ №: " + TF_Job_Number.getText() + "\n"
                + " Менеджер: "
                + ((ComboBoxDataObject) CB_Manager.getSelectedItem()).toString() + " (ID "
                + ((ComboBoxDataObject) CB_Manager.getSelectedItem()).getField1() + ");\n"
                + " Заказчик: "
                + CName + " ID(" + Integer.toString(cust_ID) + "); \n\t ТМ: " + TF_TM.getText() + ";\n";
        query = "INSERT INTO designers_jobs (Job_Number, Create_Date, ID_Manager, ID_Customer, Trade_Mark) "
                + "  VALUES ("
                + TF_Job_Number.getText() + ","
                + " NOW(), "
                + ((ComboBoxDataObject) CB_Manager.getSelectedItem()).getField1() + ", "
                + Integer.toString(cust_ID) + ", '"
                + TF_TM.getText()
                + "')";
        if (KDO_Model.getSize() > 0) {
            query2 = "INSERT INTO kind_of_job (Job_ID, kind, volume, unit)  VALUES ";

            for (int j = 0; j < KDO_Model.getSize(); j++) {
                output = output + "\t\t Вид № "
                        + Integer.toString(j + 1) + " - "
                        + ((KindDataObject) KDO_Model.getElementAt(j)).toString()
                        + "\n";
                query2 = query2 + "(-###-, '"
                        + ((KindDataObject) KDO_Model.getElementAt(j)).getKind().trim() + "', ";
                if (((KindDataObject) KDO_Model.getElementAt(j)).getVolume() == 0) {
                    query2 = query2 + "NULL, ";
                } else {
                    query2 = query2 + ((KindDataObject) KDO_Model.getElementAt(j)).getVolume_toString().replace(",", ".").trim() + ", '";
                }
                if (((KindDataObject) KDO_Model.getElementAt(j)).getUnit() == null) {
                    query2 = query2 + "NULL) ";
                } else {
                    query2 = query2 + ((KindDataObject) KDO_Model.getElementAt(j)).getUnit().trim() + "')";
                }
                if (j < KDO_Model.getSize()-1) {
                    query2 = query2 + ", ";
                }
            }
        }


        if (JOptionPane.showConfirmDialog(null, output, "Внести информацию в базу?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (JOptionPane.showConfirmDialog(null, query + query2, "Выполнить SQL запрос?",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                ConnectDB conn = new ConnectDB(SERVER, USER, PASSWORD, BASE);
                conn.init();
                try {
                    conn.iConnection.setAutoCommit(false);
                    Statement ss = conn.iConnection.createStatement();
                    int ID=0;

//                    String str = query2.replace(WldCRD, Integer.toString(ID));
//                    JOptionPane.showMessageDialog(null, "SQL =" + str);
//                    System.out.println(str);

                    ss.executeUpdate(query);
                    ResultSet result = ss.executeQuery("SELECT LAST_INSERT_ID()");
                    if (result.next()) {
                        ID = result.getInt(1);
                    }
                    JOptionPane.showMessageDialog(null, "Внесена запись с ID=" + ID);
                    query1 = query2.replace("-###-", Integer.toString(ID));
                    System.out.println(query1);
                    ss.executeUpdate(query1);
                    conn.iConnection.commit();
                    JOptionPane.showMessageDialog(null, "Внесена запись с SQL \n"
                            + query1.replace("),", "), \n"));
                } catch (SQLException ex) {
                    try {
                        conn.iConnection.rollback();
                    } catch (SQLException ex1) {
                        Logger.getLogger(JOB_Jornal_JFrame.class.getName()).log(Level.SEVERE, null, ex1);
                    }
                    JOptionPane.showMessageDialog(null, "Ошибка. ОТКАТ ТРАНЗАКЦИИ!");
                    Logger.getLogger(JOB_Jornal_JFrame.class.getName()).log(Level.SEVERE, null, ex);
                } finally{
                    try {
                        conn.iConnection.setAutoCommit(true);
                        conn.close();
                                } catch (SQLException ex) {
                        Logger.getLogger(JOB_Jornal_JFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        clearTab_1();
        TF_Job_Number.grabFocus();
    }//GEN-LAST:event_JB_AddJOBActionPerformed

    private void TF_Job_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_Job_NumberActionPerformed

    }//GEN-LAST:event_TF_Job_NumberActionPerformed

    private void TF_Job_NumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_Job_NumberFocusLost

        // подключаемся к базе и проверяем нет ли такого номера ТЗ
        try {
            int jNum = Integer.parseInt(TF_Job_Number.getText().trim());
            String Query = "CALL JobNumberIsPresent(" + TF_Job_Number.getText().trim() + ")";
            ConnectDB conn = new ConnectDB(SERVER, USER, PASSWORD, BASE);
            conn.init();
            ResultSet rs = conn.query(Query);
            try {
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "В этом году ТЗ с таким номером уже есть!!!");
                    TF_Job_Number.grabFocus();
                    TF_Job_Number.selectAll();
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Введите число в поле [№ ТЗ]");
            TF_Job_Number.grabFocus();
            TF_Job_Number.selectAll();
        }
    }//GEN-LAST:event_TF_Job_NumberFocusLost

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void CB_UnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_UnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_UnitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clearTab_1();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JOB_Jornal_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JOB_Jornal_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JOB_Jornal_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JOB_Jornal_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JOB_Jornal_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Manager;
    private javax.swing.JComboBox<String> CB_Unit;
    private javax.swing.JButton JB_AddJOB;
    private javax.swing.JButton JB_AddKind;
    private javax.swing.JLabel JL_Cust_ID;
    private javax.swing.JList<String> JL_Customers;
    private javax.swing.JList<String> JL_KindList;
    private javax.swing.JLabel LB_FIO_Redactor;
    private javax.swing.JTextField TF_Customer;
    private javax.swing.JTextField TF_Job_Number;
    private javax.swing.JTextField TF_NameOfKind;
    private javax.swing.JTextField TF_TM;
    private javax.swing.JTextField TF_Volume;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Job_Number;
    private javax.swing.JLabel jLabel_Job_Number1;
    private javax.swing.JLabel jLabel_Job_Number2;
    private javax.swing.JLabel jLabel_Job_Number3;
    private javax.swing.JLabel jLabel_Job_Number4;
    private javax.swing.JLabel jLabel_Job_Number5;
    private javax.swing.JLabel jLabel_Job_Number6;
    private javax.swing.JLabel jLabel_Job_Number7;
    private javax.swing.JLabel jLabel_Job_Number8;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void clearTab_1() {
        TF_Job_Number.setText("");
        CB_Manager.setSelectedIndex(-1);
        TF_Customer.setText("");
        TF_TM.setText("");
        TF_NameOfKind.setText("");
        TF_Volume.setText("");
        CB_Unit.setSelectedIndex(-1);
        KDO_Model.clear();
        Customer_List_Model.clear();
    }
}
